"""Add bonus_points to users

Revision ID: 33fe63206383
Revises: 9497e1ee7890
Create Date: 2025-12-11 17:08:27.194760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fe63206383'
down_revision: Union[str, None] = '9497e1ee7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bonus_points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bonus_points')
    # ### end Alembic commands ###
